### ISSUE TITLE
Firefox appears to insert vertical spacing into <pre><code>

### ISSUE THREAD

**Issue by aantron** [aantron/bisect_ppx#300]
...this affects *some* file reports. See the left image:

![unknown](https://user-images.githubusercontent.com/12073668/77892475-56bd1e80-727b-11ea-8c46-cb591ee9f375.png)

On Firefox, the lines in `<pre><code>` sometimes end up with a height of 25px, instead of 24px.

cc @ulrikstrid

**Comment by aantron** [comment]
One possible workaround is not to use the nested `<code>` tag. Then, [alternate instructions](https://highlightjs.org/usage/) for hl.js will have to be used.

**Comment by ulrikstrid** [comment]
After some testing I think it's the `Menlo` font that is the culprit.

I added a css reset from here: https://meyerweb.com/eric/tools/css/reset/ which fixed the problem and then worked backwards from there.

```css
pre, code {
	margin: 0;
	padding: 0;
	border: 0;
	font-size: 100%;
	font: inherit;
	vertical-align: baseline;
}
```
The only thing that had an effect was the `font: inherit;` so I started removing fonts.

**Comment by aantron** [comment]
I'm observing the issue on Windows with Courier New as the font rendered. Replacing that with `inherit` also does not seem to have an effect :/

**Comment by aantron** [comment]
What font gets rendered for you when you (apparently) fix the issue?

**Comment by ulrikstrid** [comment]
The weird thing is that I seem to get `Courier` so I guess that is not the fix. I found another fix however that works on my mac in firefox, chrome and safari:
```css
code {
    line-height: 20px
}
```
