### ISSUE TITLE
Question: Does it work with dune's cram test?

### ISSUE THREAD

**Issue by Kakadu** [aantron/bisect_ppx#411]
If yes, could you please add some instructions to README?

**Comment by Kakadu** [comment]
People in discord gave me a demo
https://github.com/mooreryan/bisect_ppx_cram_test_example

**Comment by aantron** [comment]
Great, thanks @Kakadu and @mooreryan! I'm going to reopen this as an issue about improving Bisect's docs.

**Comment by mbarbin** [comment]
Hi! Thank you for this issue, and linking the discord example, this helped me setup `bisect_ppx + cram` in a repo.

I struggled to make the GitHub action part work, so I'm pasting here what I currently arrived at. 

This took me a few tries! (The feedback loop when trying to debug a GitHub action is not convenient).

Putting it here if you want to discuss further, or perhaps help somebody else with that part. The part I struggled with I think was that I was afraid `/tmp` would not be available in the context of a GitHub action, and I think something wasn't working if I supply used a relative path for `BISECT_FILE`. Seems like using `runner.tmp` does the trick.

```
      - name: Run tests
        run: |
             mkdir $BISECT_DIR
             opam exec -- dune runtest --instrument-with bisect_ppx
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          BISECT_FILE: ${{ runner.temp }}/_bisect_ppx_data/data

      - name: Send coverage report to Coveralls
        run: opam exec -- bisect-ppx-report send-to Coveralls --coverage-path $BISECT_DIR
        env:
          BISECT_DIR: ${{ runner.temp }}/_bisect_ppx_data
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PULL_REQUEST_NUMBER: ${{ github.event.number }}
```

This is taken from [here](https://github.com/mbarbin/super-master-mind/blob/master/.github/workflows/ci.yml).

Thank you for the amazing bisect_ppx!
